# VASP 运行配置
potcar_dir = "~/pot/PBE"
# eledos的kmesh是scf的kmesh的2倍的密度
kmesh = 0.025
chgcar_path = "scf/CHGCAR"
wavecar_path = "scf/WAVECAR"

[vasp]
executable_path = "mpirun -np 48 vasp_std"

# Slurm 提交脚本配置
[slurm]
header = """
#!/bin/sh
#SBATCH  --job-name=mayuan
#SBATCH  --output=log.out
#SBATCH  --error=log.err
#SBATCH  --partition=liuhanyu
#SBATCH  --nodes=1
#SBATCH  --ntasks=48
#SBATCH  --ntasks-per-node=48
#SBATCH  --cpus-per-task=1
#SBATCH  --exclude=node49,node98,node57

source /work/home/mayuan/intel/oneapi/setvars.sh --force
ulimit -s unlimited
export I_MPI_ADJUST_REDUCE=3
export MPIR_CVAR_COLL_ALIAS_CHECK=0
"""

# INCAR 参数自定义 (会覆盖脚本内的默认值)
[incar_params]
ENCUT = 520
ISMEAR = 0
SIGMA = 0.05
EDIFF = 1e-8
LREAL = "Auto"